name: Generate Android APK

on:
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "new" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17 
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      # We point directly to the file in the subfolder
      run: chmod +x SampleCode-V5/android-sdk-v5-as/gradlew

    - name: Build Debug APK
      # We run the command inside the specific directory
      run: ./gradlew assembleDebug
      working-directory: SampleCode-V5/android-sdk-v5-as

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        # This will search all folders for the resulting .apk
        path: "**/build/outputs/apk/debug/*.apk"
